### ISSUE TITLE
Ukol c.1

### ISSUE THREAD

**Issue by B4runk4** [B4runk4/python-kurz-2022#1]
https://github.com/B4runk4/python-kurz-2022/blob/main/ukol-1.py

Odevzdavam ukol c.1

**Comment by pmoravkova** [comment]
Jsi na dobre ceste, akorat to nesplnuje zadani. Ty tu jen vypises ten slovnik, akorat to nahradis vypisem, jestli balik byl predan nebo nebyl kuryrovi. Akorat dle zadani bys mela udelat program, ktery se zepta na cislo baliku, a na zaklade toho cisla vypise, jestli byl balik jiz predan nebo ne. Takze urcite zacni inputem:
`balik = input('Zadej cislo baliku: ')`
a pak budes hledat, zda ta promenna balik byla ci nebyla predana kuryrovi. (Idealne jeste jestli vubec cislo baliku existuje.)
Tip:
`== True` je v podmince zbytecne, staci napsat if z:, kdyz to vyhodnoti jako True, coz bude, jakmile je hodnota k tomu klici True, tak je podminka splnena.
z + 1 je uplne zbytecne a v tomto kodu nedela vubec nic. To, ze se z posune o dalsi radek ve slovniku, je zajisteno tim `for z in baliky`

**Comment by B4runk4** [comment]
diky za zpetnou vazbu, po dnesni lekci na to jeste kouknu. Abych rekla pravdu, dalo mi zabrat samotne nastavovani githubu, instalace vs code a tak, protoze jsem minule chybela... takze jsem tuhle cast zadani nejak prehlidla :/ takze to jeste opravim

**Comment by pmoravkova** [comment]
Uplne v pohode, mas na to tyden jeste, myslim. Navic ja to pocitam jako odevzdany, i kdyz to neni 100% spravny reseni. 
Budiz ti utechou, ze dalsi tohle nastavovani uz vas (pokud na data nebudete pouzivat jupyter notebook, to priznavam, ze nevim). Kazdopadne kdybys narazila na nejaky problem, nebo cokoliv s nastavovanim, tak staci napsat na slacku a poradime, muzem to pak i nekdy pred/po hodine projit nebo tak.

**Comment by B4runk4** [comment]
https://github.com/B4runk4/python-kurz-2022/blob/main/ukol-1.py

Tady jsem udelala nejake zmeny, ale mam pocit, ze to jeste neni ono... nasmerovala bys me dal? :) diky

**Comment by pmoravkova** [comment]
Skvele! Mas to presne, jak se to chtelo. Prijde uzivatel, zepta se ho to na cislo baliku, on zada cislo baliku a dostane spravnou odpoved. Dobra prace!
Tip:
Neni to sice v zadani, ale je to dobre do praxe: Vzdy se snazit osetrit, aby program nespadl, ale skoncil s nejakou smysluplnou hlaskou. V tomhle pripade je by bylo dobry osetrit, co se stane, kdyz uzivatel zada spatne cislo baliku, co neni v seznamu. K naproste dokonalosti by to chtelo, aby program nespadl, ale vratil mu hlasku, ze balik neexistuje. Ale je to nad ramec zadani, jen je dobre na to myslet. :)
